version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Dev/joel-hoelting-api
    runas: ubuntu
# hooks:
#   BeforeInstall:
#     - location: scripts/before
#       timeout: 300
#       runas: 777
